import {Vehicle} from "../../components/VehicleGrid.tsx";

export const data: Vehicle[] = [
  {
    id: 1030315,
    photo: 'https://images.turo.com/media/vehicle/images/Rz5Ynm9YQhGZgNI6dSo_Vg.1440x700.jpg',
    car: 'Chevrolet Corvette',
    year: 2021,
    price: 135,
    dayPrice: { price: 128, discount: 5 },
    weekPrice: { price: 122, discount: 10 },
    monthPrice: { price: 115, discount: 15 },
    deliveryPrice: 90,
    available: 18,
    notAvailable: 13,
    activeListing: 'true',
    color: 'RED',
    tripCount: 344,
    numberOfFavorites: 3454,
    numberOfReviews: 128,
    url: 'https://turo.com/gb/en/car-rental/united-states/dania-beach-fl/chevrolet/corvette/1030315',
  },
  {
    id: 2040326,
    photo: 'https://example.com/media/vehicle/images/uniqueImageID1.jpg',
    car: 'Tesla Model S',
    year: 2022,
    price: 150,
    dayPrice: { price: 140, discount: 7 },
    weekPrice: { price: 130, discount: 13 },
    monthPrice: { price: 120, discount: 20 },
    deliveryPrice: 100,
    available: 20,
    notAvailable: 10,
    activeListing: 'true',
    color: 'BLACK',
    tripCount: 500,
    numberOfFavorites: 4000,
    numberOfReviews: 150,
    url: 'https://example.com/car-rental/united-states/city-state/tesla/model-s/2040326',
  },
  {
    id: 3050437,
    photo: 'https://example.com/media/vehicle/images/uniqueImageID2.jpg',
    car: 'Ford Mustang',
    year: 2019,
    price: 120,
    dayPrice: { price: 114, discount: 5 },
    weekPrice: { price: 108, discount: 10 },
    monthPrice: { price: 102, discount: 15 },
    deliveryPrice: 85,
    available: 15,
    notAvailable: 5,
    activeListing: 'true',
    color: 'BLUE',
    tripCount: 250,
    numberOfFavorites: 2300,
    numberOfReviews: 95,
    url: 'https://example.com/car-rental/united-states/city-state/ford/mustang/3050437',
  },
  {
    id: 4060548,
    photo: 'https://example.com/media/vehicle/images/uniqueImageID3.jpg',
    car: 'BMW M3',
    year: 2020,
    price: 165,
    dayPrice: { price: 157, discount: 5 },
    weekPrice: { price: 149, discount: 10 },
    monthPrice: { price: 141, discount: 15 },
    deliveryPrice: 110,
    available: 12,
    notAvailable: 8,
    activeListing: 'true',
    color: 'WHITE',
    tripCount: 300,
    numberOfFavorites: 3200,
    numberOfReviews: 120,
    url: 'https://example.com/car-rental/united-states/city-state/bmw/m3/4060548',
  },
  {
    id: 5070659,
    photo: 'https://example.com/media/vehicle/images/uniqueImageID4.jpg',
    car: 'Audi R8',
    year: 2023,
    price: 200,
    dayPrice: { price: 190, discount: 5 },
    weekPrice: { price: 180, discount: 10 },
    monthPrice: { price: 170, discount: 15 },
    deliveryPrice: 120,
    available: 10,
    notAvailable: 2,
    activeListing: 'true',
    color: 'SILVER',
    tripCount: 550,
    numberOfFavorites: 4500,
    numberOfReviews: 200,
    url: 'https://example.com/car-rental/united-states/city-state/audi/r8/5070659',
  },
  {
    id: 6080760,
    photo: 'https://example.com/media/vehicle/images/uniqueImageID5.jpg',
    car: 'Porsche 911',
    year: 2021,
    price: 180,
    dayPrice: { price: 172, discount: 4 },
    weekPrice: { price: 164, discount: 9 },
    monthPrice: { price: 156, discount: 13 },
    deliveryPrice: 95,
    available: 8,
    notAvailable: 7,
    activeListing: 'true',
    color: 'YELLOW',
    tripCount: 400,
    numberOfFavorites: 3600,
    numberOfReviews: 140,
    url: 'https://example.com/car-rental/united-states/city-state/porsche/911/6080760',
  },
  {
    id: 7090871,
    photo: 'https://example.com/media/vehicle/images/uniqueImageID6.jpg',
    car: 'Lexus LC500',
    year: 2018,
    price: 140,
    dayPrice: { price: 134, discount: 4 },
    weekPrice: { price: 128, discount: 8 },
    monthPrice: { price: 122, discount: 13 },
    deliveryPrice: 80,
    available: 22,
    notAvailable: 3,
    activeListing: 'true',
    color: 'ORANGE',
    tripCount: 220,
    numberOfFavorites: 2100,
    numberOfReviews: 85,
    url: 'https://example.com/car-rental/united-states/city-state/lexus/lc500/7090871',
  },
  {
    id: 8100982,
    photo: 'https://example.com/media/vehicle/images/uniqueImageID7.jpg',
    car: 'Mercedes-Benz G-Class',
    year: 2022,
    price: 220,
    dayPrice: { price: 210, discount: 5 },
    weekPrice: { price: 200, discount: 9 },
    monthPrice: { price: 190, discount: 14 },
    deliveryPrice: 130,
    available: 14,
    notAvailable: 6,
    activeListing: 'true',
    color: 'GREEN',
    tripCount: 320,
    numberOfFavorites: 2900,
    numberOfReviews: 110,
    url: 'https://example.com/car-rental/united-states/city-state/mercedes-benz/g-class/8100982',
  },
  {
    id: 9111093,
    photo: 'https://example.com/media/vehicle/images/uniqueImageID8.jpg',
    car: 'Nissan GT-R',
    year: 2017,
    price: 170,
    dayPrice: { price: 162, discount: 5 },
    weekPrice: { price: 154, discount: 9 },
    monthPrice: { price: 146, discount: 14 },
    deliveryPrice: 105,
    available: 16,
    notAvailable: 4,
    activeListing: 'true',
    color: 'GREY',
    tripCount: 275,
    numberOfFavorites: 2500,
    numberOfReviews: 100,
    url: 'https://example.com/car-rental/united-states/city-state/nissan/gt-r/9111093',
  },
  {
    id: 10120104,
    photo: 'https://example.com/media/vehicle/images/uniqueImageID9.jpg',
    car: 'Chevrolet Camaro',
    year: 2020,
    price: 110,
    dayPrice: { price: 105, discount: 4.5 },
    weekPrice: { price: 100, discount: 9 },
    monthPrice: { price: 95, discount: 13.5 },
    deliveryPrice: 75,
    available: 18,
    notAvailable: 2,
    activeListing: 'true',
    color: 'PURPLE',
    tripCount: 190,
    numberOfFavorites: 2000,
    numberOfReviews: 80,
    url: 'https://example.com/car-rental/united-states/city-state/chevrolet/camaro/10120104',
  },
  {
    id: 11131115,
    photo: 'https://example.com/media/vehicle/images/uniqueImageID10.jpg',
    car: 'Jaguar F-Type',
    year: 2025, // Assuming a future booking for a model released early
    price: 190,
    dayPrice: { price: 181, discount: 4.7 },
    weekPrice: { price: 172, discount: 9.4 },
    monthPrice: { price: 163, discount: 14.1 },
    deliveryPrice: 110,
    available: 9,
    notAvailable: 5,
    activeListing: 'true',
    color: 'METALLIC RED',
    tripCount: 100,
    numberOfFavorites: 1500,
    numberOfReviews: 50,
    url: 'https://example.com/car-rental/united-states/city-state/jaguar/f-type/11131115',
  }
]
