import {Vehicle} from "../../components/VehicleGrid";

export const data: Vehicle[] = [
  {
    id: 1030315,
    photo: 'https://images.turo.com/media/vehicle/images/Rz5Ynm9YQhGZgNI6dSo_Vg.1440x700.jpg',
    car: { name: 'Chevrolet Corvette', url: 'https://turo.com/gb/en/car-rental/united-states/dania-beach-fl/chevrolet/corvette/1030315' },
    year: 2021,
    price: 135,
    dayPrice: { price: 128, discount: 5 },
    weekPrice: { price: 122, discount: 10 },
    monthPrice: { price: 115, discount: 15 },
    deliveryPrice: { price: 90, freeIf: 'Free delivery to select locations for trips of 3 days or longer' },
    available: 18,
    notAvailable: 13,
    activeListing: true,
    color: 'RED',
    tripCount: 344,
    numberOfFavorites: 3454,
    numberOfReviews: 128,
    isMyCar: false,
    state: 'Florida',
  },
  {
    id: 2563747,
    photo: 'https://images.turo.com/media/vehicle/images/GpOqYPl3Rf-RSFNbZxdHeg.2880x1400.jpg',
    car: { name: 'Cadillac Escalade ESV', url: 'https://turo.com/us/en/suv-rental/united-states/dania-beach-fl/cadillac/escalade-esv/2563747?endDate=04%2F12%2F2024&endTime=10%3A00&startDate=04%2F09%2F2024&startTime=10%3A00' },
    year: 2022,
    price: 151,
    dayPrice: { price: 146, discount: 3 },
    weekPrice: { price: 140, discount: 7 },
    monthPrice: { price: 121, discount: 20 },
    deliveryPrice: { price: 95, freeIf: 'Free delivery to select locations for trips of 3 days or longer' },
    available: 25,
    notAvailable: 6,
    activeListing: true,
    color: 'BLACK',
    tripCount: 6,
    numberOfFavorites: 36,
    numberOfReviews: 6,
    isMyCar: true,
    state: 'Florida',
  },
  {
    id: 2556146,
    photo: 'https://images.turo.com/media/vehicle/images/EiDusyCAQXi-XvKYd_O0Wg.1440x700.jpg',
    car: { name: 'BMW X7', url: 'https://turo.com/us/en/suv-rental/united-states/dania-beach-fl/bmw/x7/2556146?endDate=04%2F12%2F2024&endTime=10%3A00&startDate=04%2F09%2F2024&startTime=10%3A00' },
    year: 2022,
    price: 103,
    dayPrice: { price: 100, discount: 3 },
    weekPrice: { price: 96, discount: 7 },
    monthPrice: { price: 82, discount: 20 },
    deliveryPrice: { price: 95, freeIf: 'Free delivery to select locations for trips of 4 days or longer' },
    available: 22,
    notAvailable: 9,
    activeListing: true,
    color: 'WHITE',
    tripCount: 9,
    numberOfFavorites: 66,
    numberOfReviews: 7,
    isMyCar: true,
    state: 'Florida',
  },
  {
    id: 2577104,
    photo: 'https://images.turo.com/media/vehicle/images/G1AnSHP6Sz-jiDZTIpbaaQ.1440x700.jpg',
    car: { name: 'BMW X7', url: 'https://turo.com/us/en/suv-rental/united-states/dania-beach-fl/bmw/x7/2577104?endDate=04%2F12%2F2024&endTime=10%3A00&startDate=04%2F09%2F2024&startTime=10%3A00' },
    year: 2023,
    price: 106,
    dayPrice: { price: 103, discount: 3 },
    weekPrice: { price: 99, discount: 7 },
    monthPrice: { price: 90, discount: 15 },
    deliveryPrice: { price: 100, freeIf: 'Free delivery to select locations for trips of 3 days or longer' },
    available: 26,
    notAvailable: 5,
    activeListing: true,
    color: 'GRAY',
    tripCount: 5,
    numberOfFavorites: 32,
    numberOfReviews: 4,
    isMyCar: true,
    state: 'Florida',
  },
  {
    id: 2578088,
    photo: 'https://images.turo.com/media/vehicle/images/DpqEIJX8RYCsTKU5RMdgKw.2880x1400.jpg',
    car: { name: 'BMW X7', url: 'https://turo.com/us/en/suv-rental/united-states/dania-beach-fl/bmw/x7/2578088?endDate=04%2F12%2F2024&endTime=10%3A00&startDate=04%2F09%2F2024&startTime=10%3A00' },
    year: 2023,
    price: 106,
    dayPrice: { price: 103, discount: 3 },
    weekPrice: { price: 99, discount: 7 },
    monthPrice: { price: 90, discount: 15 },
    deliveryPrice: { price: 100, freeIf: 'Free delivery to select locations for trips of 3 days or longer' },
    available: 27,
    notAvailable: 4,
    activeListing: true,
    color: 'BLACK',
    tripCount: 4,
    numberOfFavorites: 19,
    numberOfReviews: 4,
    isMyCar: true,
    state: 'Florida',
  },
  {
    id: 2579777,
    photo: 'https://images.turo.com/media/vehicle/images/502eSIDAS6SvlkZN4z24KQ.2880x1400.jpg',
    car: { name: 'BMW X6', url: 'https://turo.com/us/en/suv-rental/united-states/dania-beach-fl/bmw/x6/2579777?endDate=04%2F12%2F2024&endTime=10%3A00&startDate=04%2F09%2F2024&startTime=10%3A00' },
    year: 2024,
    price: 103,
    dayPrice: { price: 100, discount: 3 },
    weekPrice: { price: 96, discount: 7 },
    monthPrice: { price: 88, discount: 15 },
    deliveryPrice: { price: 95, freeIf: 'Free delivery to select locations for trips of 4 days or longer' },
    available: 27,
    notAvailable: 4,
    activeListing: true,
    color: 'BACK',
    tripCount: 4,
    numberOfFavorites: 107,
    numberOfReviews: 4,
    isMyCar: true,
    state: 'Florida',
  },
  {
    id: 7090871,
    photo: 'https://example.com/media/vehicle/images/uniqueImageID6.jpg',
    car: { name: 'Lexus LC500', url: null },
    year: 2018,
    price: 140,
    dayPrice: { price: 134, discount: 4 },
    weekPrice: { price: 128, discount: 8 },
    monthPrice: { price: 122, discount: 13 },
    deliveryPrice: { price: 95, freeIf: 'Free delivery to select locations for trips of 5 days or longer' },
    available: 22,
    notAvailable: 3,
    activeListing: false,
    color: 'ORANGE',
    tripCount: 220,
    numberOfFavorites: 2100,
    numberOfReviews: 85,
    isMyCar: false,
    state: 'Florida',
  },
  {
    id: 8100982,
    photo: 'https://example.com/media/vehicle/images/uniqueImageID7.jpg',
    car: { name: 'Mercedes-Benz G-Class', url: null },
    year: 2022,
    price: 220,
    dayPrice: { price: 210, discount: 5 },
    weekPrice: { price: 200, discount: 9 },
    monthPrice: { price: 190, discount: 14 },
    deliveryPrice: { price: 75, freeIf: 'Free delivery to select locations for trips of 4 days or longer' },
    available: 14,
    notAvailable: 6,
    activeListing: false,
    color: 'GREEN',
    tripCount: 320,
    numberOfFavorites: 2900,
    numberOfReviews: 110,
    isMyCar: false,
    state: 'Florida',
  },
  {
    id: 9111093,
    photo: 'https://example.com/media/vehicle/images/uniqueImageID8.jpg',
    car: { name: 'Nissan GT-R', url: null },
    year: 2017,
    price: 170,
    dayPrice: { price: 162, discount: 5 },
    weekPrice: { price: 154, discount: 9 },
    monthPrice: { price: 146, discount: 14 },
    deliveryPrice: { price: 105, freeIf: 'Free delivery to select locations for trips of 4 days or longer' },
    available: 16,
    notAvailable: 4,
    activeListing: false,
    color: 'GREY',
    tripCount: 275,
    numberOfFavorites: 2500,
    numberOfReviews: 100,
    isMyCar: false,
    state: 'Florida',
  },
  {
    id: 10120104,
    photo: 'https://example.com/media/vehicle/images/uniqueImageID9.jpg',
    car: { name: 'Chevrolet Camaro', url: null },
    year: 2020,
    price: 110,
    dayPrice: { price: 105, discount: 4.5 },
    weekPrice: { price: 100, discount: 9 },
    monthPrice: { price: 95, discount: 13.5 },
    deliveryPrice: { price: 90, freeIf: 'Free delivery to select locations for trips of 3 days or longer' },
    available: 18,
    notAvailable: 2,
    activeListing: false,
    color: 'PURPLE',
    tripCount: 190,
    numberOfFavorites: 2000,
    numberOfReviews: 80,
    isMyCar: false,
    state: 'Florida',
  },
  {
    id: 11131115,
    photo: 'https://example.com/media/vehicle/images/uniqueImageID10.jpg',
    car: { name: 'Jaguar F-Type', url: null },
    year: 2024,
    price: 190,
    dayPrice: { price: 181, discount: 4.7 },
    weekPrice: { price: 172, discount: 9.4 },
    monthPrice: { price: 163, discount: 14.1 },
    deliveryPrice: { price: 100, freeIf: 'Free delivery to select locations for trips of 4 days or longer' },
    available: 9,
    notAvailable: 5,
    activeListing: false,
    color: 'METALLIC RED',
    tripCount: 100,
    numberOfFavorites: 1500,
    numberOfReviews: 50,
    isMyCar: false,
    state: 'Florida',
  }
]
